name: PV-EV-model
channels:
  - conda-forge
  - defaults
  - cmutel
  - bsteubing
  - haasad
  - pascallesage
dependencies:
  - python=3.7
  - weasyprint
  - libsqlite
  - jupyter_client
  - ca-certificates
  - wheel
  - colorama
  - psutil
  - vc
  - zeromq
  - backcall
  - debugpy
  - python_abi
  - jupyter_core
  - parso
  - python-dateutil
  - openssl
  - ucrt
  - setuptools
  - vs2015_runtime
  - pygments
  - nest-asyncio
  - six
  - jedi
  - backports.functools_lru_cache
  - matplotlib-inline
  - pywin32
  - pyparsing
  - sqlite
  - pip
  - packaging
  - ipython
  - libsodium
  - traitlets
  - backports
  - wcwidth
  - pyzmq
  - tornado
  - pickleshare
  - prompt-toolkit
  - decorator
  - entrypoints
  - ipykernel
